# Generated by Django 6.0.7 on 2026-07-20 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ExpressionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('track_type', models.CharField(choices=[('SLANG', 'Slangman'), ('STREET', 'Street Talk'), ('BIZ', 'BizTalk'), ('TALK', 'Talk Talk Talk'), ('BLEEP', 'Bleep/Taboo'), ('DECODER', 'Culture Decoder')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VideoContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(help_text='The 11-character ID at the end of a YouTube link', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='simulator.category')),
                ('expression_modules', models.ManyToManyField(blank=True, related_name='videos', to='simulator.expressionmodule')),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('timestamp_seconds', models.PositiveIntegerField(help_text='The exact second this phrase appears in the video')),
                ('literal_meaning', models.TextField(help_text='What the words mean on the surface.')),
                ('native_subtext', models.TextField(help_text='The REAL hidden meaning native speakers understand.')),
                ('social_context', models.TextField(blank=True, help_text='Why a native speaker uses this.')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='simulator.expressionmodule')),
                ('video_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='simulator.videocontext')),
            ],
        ),
    ]
