# Generated by Django 6.0.7 on 2026-07-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description for the category.', max_length=1000),
        ),
        migrations.CreateModel(
            name='SavedExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='simulator.expression')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_expressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'expression')},
            },
        ),
    ]
