# Generated by Django 6.0.6 on 2026-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_category_description_savedexpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedexpression',
            name='status',
            field=models.CharField(choices=[('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='learning', max_length=20),
        ),
        migrations.AddField(
            model_name='savedexpression',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags e.g. #Sarcasm, #Business', max_length=200),
        ),
    ]
