# Generated by Django 6.0.6 on 2026-07-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_savedexpression_status_savedexpression_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.PositiveIntegerField()),
                ('speaker', models.CharField(blank=True, help_text='e.g. Speaker A', max_length=100)),
                ('text', models.TextField()),
                ('video_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_lines', to='simulator.videocontext')),
            ],
            options={
                'ordering': ['timestamp_seconds'],
            },
        ),
    ]
