# Generated by Django 6.0.7 on 2026-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_transcriptline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptline',
            name='speaker',
            field=models.CharField(blank=True, help_text='e.g. Speaker A', max_length=100, null=True),
        ),
    ]
