# Generated by Django 6.0.7 on 2026-07-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_alter_transcriptline_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptline',
            name='end_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Secondes de fin'),
        ),
        migrations.AlterField(
            model_name='transcriptline',
            name='timestamp_seconds',
            field=models.PositiveIntegerField(help_text='Secondes de début'),
        ),
    ]
