# Generated by Django 6.0.7 on 2026-07-21 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Video Comprehension Test', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text="Instructions globales pour l'évaluation.")),
                ('video_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='simulator.videocontext')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Score obtenu (sur 40 par exemple)')),
                ('max_score', models.PositiveIntegerField(default=40)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answers_data', models.TextField(blank=True, help_text="Stockage des réponses de l'étudiant")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulator.videoassessment')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
