# Generated by Django 6.0.7 on 2026-07-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_videoassessment_studentassessmentattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='score',
            field=models.PositiveIntegerField(help_text='Score obtenu'),
        ),
        migrations.AlterField(
            model_name='videoassessment',
            name='instructions',
            field=models.TextField(blank=True, help_text="Consignes globales de l'exercice."),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField(default=1, help_text='Numéro de la partie (ex: 1 pour Global, 2 pour Détail...)')),
                ('question_text', models.TextField(help_text='Énoncé de la question')),
                ('question_type', models.CharField(choices=[('TEXT', 'Réponse libre / Développement (ex: Part 1 & 4)'), ('TRUE_FALSE', 'Vrai / Faux avec Justification (ex: Part 2)'), ('CHOICE', 'Choix multiples (QCM)')], default='TEXT', max_length=20)),
                ('points', models.PositiveIntegerField(default=5, help_text='Nombre de points pour cette question')),
                ('requires_justification', models.BooleanField(default=False, help_text='Cocher si une justification textuelle est exigée (pour le Vrai/Faux)')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de la question")),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='simulator.videoassessment')),
            ],
            options={
                'ordering': ['part_number', 'order'],
            },
        ),
    ]
