# Generated by Django 6.0.7 on 2026-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_alter_studentassessmentattempt_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='feedback',
            field=models.TextField(blank=True, help_text='Commentaires du professeur sur la copie'),
        ),
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='is_graded',
            field=models.BooleanField(default=False, help_text='Cocher si la copie a été corrigée et notée'),
        ),
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='answers_data',
            field=models.TextField(blank=True, help_text="Stockage des réponses de l'étudiant (JSON)"),
        ),
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Score obtenu'),
        ),
    ]
