# Generated by Django 6.0.7 on 2026-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_studentassessmentattempt_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='options',
            field=models.TextField(blank=True, help_text='Entre les options de réponse séparées par un retour à la ligne (pour les QCM).'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Réponse libre / Développement (ex: Part 1 & 4)'), ('TRUE_FALSE', 'Vrai / Faux avec Justification (ex: Part 2)'), ('QCM', 'Question à Choix Multiples (QCM)')], default='TEXT', max_length=20),
        ),
    ]
