# Generated by Django 6.0.7 on 2026-07-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_assessmentquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='correct_answer',
            field=models.TextField(blank=True, help_text="Réponse attendue ou critères de correction pour l'auto-évaluation par l'IA"),
        ),
    ]
